name: Example Push Action
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git stash
          git fetch
          git checkout ci
          git stash pop
          git add .
          git commit -m "generated"
          git push